---

- name: install mesos RPM and deps
  yum: name={{ item }} state=present
  with_items:
    - "{{ mesos_rpm }}"
    - cyrus-sasl
  notify: bounce mesos

- name: mesos work dir
  file: path={{ mesos_work_dir }} state=directory

- name: setup zookeeper config
  template: src=etc/mesos/zk.j2 dest=/etc/mesos/zk
            mode=0444
  notify: bounce mesos
