
- name: configure master
  template: src=.{{ item }}.j2  dest={{ item }}
            mode=0444
  with_items:
    - /etc/mesos-master/work_dir
    - /etc/mesos-master/quorum
    - /etc/mesos-master/registry
  notify: bounce mesos

- name: mesos master service
  service: name=mesos-master state=running enabled=yes

- name: lose mesos-slave upstart script
  file: name=/etc/init/mesos-slave.conf state=absent
