# needed by masters and slaves (since 0.19)
mesos_work_dir: /var/mesos
# default from RPM
mesos_log_dir: /var/log/mesos
mesos_maxfiles: 64000

# slave specific

# experimental: swap for the commented one if need be
mesos_isolation: cgroups/cpu,cgroups/mem
#mesos_isolation: posix/cpu,posix/mem
